### ISSUE TITLE
Two minor glitches within a57a1809 (Add variables mapping for gfs)

### ISSUE THREAD

**Issue by amotl** [earthobservations/GribMagic#2]
Dear Daniel,

within a57a1809, I've added two comments about minor glitches within `model_variables_mapping.yml` and `unified_forecast_variables.py`. Hope this helps.

With kind regards,
Andreas.

**Comment by meteoDaniel** [comment]
@amotl  thanks for your hint. I will finish the processeing of KNMI_HARMONIe weather model. Afterwards I will start to work with PR to move more and more to a first working version

**Comment by amotl** [comment]
Dear Daniel,

I just checked and both typos are still there:

- https://github.com/earthobservations/GribMagic/commit/a57a1809f734f9e9674cbc63b2d503a082846ab3#r40408704
- https://github.com/earthobservations/GribMagic/commit/a57a1809f734f9e9674cbc63b2d503a082846ab3#r40408861

JFYI.

With kind regards,
Andreas.
