### ISSUE TITLE
DWD COSMO-D2: Data is published in multiple grid variants

### ISSUE THREAD

**Issue by amotl** [earthobservations/gribmagic#4]
Hi again,

we just found that data of DWD COSMO-D2 within the "temperature 2m" folder [1] is published with multiple grid variants like `regular-lat-lon` vs. `rotated-lat-lon`.

Parameter folders for "temperature" [2] also bring in the levels-axis like `model-level` vs. `pressure-level` as outlined within #3, so this folder and friends contains four (4) different sets of data in total.

As @mhaberler pointed out at https://github.com/earthobservations/gribmagic/issues/3#issuecomment-748515557, the [docker-dwd-open-data-downloader](https://github.com/EduardRosert/docker-dwd-open-data-downloader) by @EduardRosert also accounts for that by discriminating between `"grids": ["regular-lat-lon", "rotated-lat-lon"]`, see [models.json](https://github.com/EduardRosert/docker-dwd-open-data-downloader/blob/master/models.json).

With kind regards,
Andreas.

[1] https://opendata.dwd.de/weather/nwp/cosmo-d2/grib/00/t_2m/
[2] https://opendata.dwd.de/weather/nwp/cosmo-d2/grib/00/t/

**Comment by mhaberler** [comment]
[I also found 'icosahedral'](https://opendata.dwd.de/weather/nwp/icon-d2/grib/12/hhl/icon-d2_germany_icosahedral_time-invariant_2020122012_000_10_hhl.grib2.bz2) which is the native grid of these Icon-type models

**Comment by mhaberler** [comment]
note Cosmo-D2 is on the way out and is currently being replaced by Icon-D2 which is sort-of preproduction status (but stable as far as I can judge)

**Comment by amotl** [comment]
With #14, we are integrating the DWD GRIB Downloader and wrapping its features.
